apiVersion: cache.azure.upbound.io/v1beta1
kind: RedisCache
metadata:
  name: crossplane-redis-demo
spec:
  forProvider:
    location: "centralindia"
    resourceGroupName: bakery-mcp-demo
    capacity: 2
    family: "C"
    skuName: "Basic"
    redisVersion: "6"
    enableNonSslPort: false
  providerConfigRef:
    name: default
